### PR TITLE
Weather app

### PR DESCRIPTION
**Pull request by alvarorf**
This weather app:
- Fetches data from the openweather API and displays it nicely in the screen.
- Uses webpack and ES6 syntax.
- Uses the giphy API to display a gif related to the current climate.

Notes: 
- Aside from executing "npm install" to install the dependencies, run "npm run local" to run the local version of the project, and then go to "http://localhost:5000/dist/" in your web browser.

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨

- Nice design, and good work structure to begin with.

## However, there are some changes required 👀 🧰 🔨 🔧
- When I click on the `Get weather data` button, I get the following error on the console:
image
- Please fix this bug. And also, please add some error handling to your code so that the console doesn't generate an exception when the API responds with a failure code.

***[ OPTIONAL: ]***

- Please, let's use code modulation to separate your app components: use separate files for DOM, API and app logic.


### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @alvarorf :wave: 

When I enter a city or country, it does return any weather information. Kindly use this gif for reference.

notworking

#### Please effect this change, then submit another form for a code review.

### Happy coding :technologist: 

#### ``` Uchechukwu Henry Inyama ```

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello  Álvaro Ruiz Flórez** 
Good job with the improvements for this project :muscle:  :muscle:
There is one detail to improve before you can go ahead:
- [x] Like the previous TSE, I couldn't get any data after trying some valid cities. Did you update your Live Demo?
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔✔✔**

Hello @alvarorf ,
Great implementation of the project.
You can merge. 👍👍👌👌

Happy coding💻💻💻💻💻

**Pull request merged**
